### ISSUE TITLE
로그인 형식에 관한 이슈 (기존 비밀번호 불가 현상)

### ISSUE THREAD

**Issue by JengYoung** [prgrms-web-devcourse/Team_Everevent_Kazedon_FE#107]
## 이슈 설명
현재 기존 비밀번호에 대해 로그인을 할 수 없는 현상이 발생하고 있습니다.
혹시, 로그인 비밀번호에 관하여, 반드시 형식을 지키도록 해야 하나요?
(만약 그렇다면, 나중에 반드시 비밀번호 찾기가 구현되어야 할 것 같아요! 제 그리운 첫 아이디를 사용하지 못하고 있답니다 😂)

**Comment by Sunjae95** [comment]
이 문제는 DB확인해보니 테스트하면서 싹 한번 지우셨다고 합니다! 없는게 당연하구 그립지만 보내주죠...ㅠㅠ

**Comment by JengYoung** [comment]
@Sunjae95 따흑.... 그렇군요!! 마음이 아프군유 😂

**Comment by JengYoung** [comment]
그럼 이슈는 종료하게씁니다!
