### ISSUE TITLE
CSS font 적용 중 이슈 발생

### ISSUE THREAD

**Issue by JengYoung** [prgrms-web-devcourse/Team_Everevent_Kazedon_FE#34]
## 문제

CSS font를 글로벌하게 적용하는 중 `css` 파일에서 전역으로 등록한 부분이 제대로 반영되지 않는 문제가 발생했습니다.
`!important`를 하면 해결이 되지만, 이는 최대한 지양하는 방법이므로 다른 방안을 찾고 있는 중입니다.

~~현재 `CSS`를 통한 폰트 로딩은 해결했지만, `preload` 부분에 관련한 이슈가 발생했습니다. ('FOUT')
혹시, 폰트 프리로딩에 대해 잘 아시는 분 있으실까요?~~

> ### 해결 완료했습니다!😂

### 1. 전역에 `head`로 `link` 태그 전달하기
`_app.tsx`에 `Head`를 집어 넣어준다.
```tsx
    <>
      <Head>
        <link rel="preconnect" href="https://fonts.googleapis.com" as="font" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="true"
        />
        <link
          rel="preload"
          as="style"
          type="text/css"
          href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@400;700&display=swap"
        />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@400;700&display=swap"
        />
      </Head>
      <Component {...pageProps} />
    </>
```

### 2. `font-display` 속성 바꾸기
기존 폰트를 보면, 수상한 부분이 보입니다.
```html
<link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@400;700&display=swap" rel="stylesheet">
```
**여기서 `display=swap`은 무엇일까요?**
[MDN 공식 문서의 font-display](https://developer.mozilla.org/ko/docs/Web/CSS/@font-face/font-display)에서는 다음과 같이 서술되어 있습니다.
짧게 요약하자면, 해당 폰트에 대한 차단 및 교체 시간을 조절해주는 힌트라고 볼 수 있습니다.
현재는 매우 짧은 차단 기간을 갖고 있습니다. 따라서 살짝 덜 차단 기간이 짧은 `block`으로 설정을 하였습니다.
```tsx
import '@styles/globals.css';
import type { AppProps } from 'next/app';
import Head from 'next/head';

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <link rel="preconnect" href="https://fonts.googleapis.com" as="font" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="true"
        />
        <link
          rel="preload"
          as="style"
          type="text/css"
          href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@400;700&display=block"
        />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@400;700&display=block"
        />
      </Head>
      <Component {...pageProps} />
    </>
  );
}

export default MyApp;

```

이를 적용한 결과, 성공적으로 preload가 제대로 적용되어, `FOUT`으로 인한 폰트 교체가 눈에 보이지 않습니다.
## 시연 영상
![font-display](https://user-images.githubusercontent.com/78713176/145065192-c368ec8d-8a0c-42b3-8ad4-83dc8c4b2851.gif)

### CSS 파일을 직접 `globalStyle`에 넣었을 경우
![image](https://user-images.githubusercontent.com/78713176/145060409-881ae02f-d60a-4db8-b664-8fec5d81e7b8.png)

### `preload`를 통해 힌트를 주고 css파일을 가져올 경우
![image](https://user-images.githubusercontent.com/78713176/145062024-e9594676-de70-4836-a99e-2d758e787fe1.png)

더 빠른 결과가 후자라, 후자를 택합니다!

## 참고 자료
https://stackoverflow.com/questions/50824181/preloading-google-fonts
https://velog.io/@vnthf/%EC%9B%B9%ED%8F%B0%ED%8A%B8-%EC%B5%9C%EC%A0%81%ED%99%94-%ED%95%98%EA%B8%B0
https://developer.mozilla.org/ko/docs/Web/CSS/@font-face/font-display

**Comment by JengYoung** [comment]
@Sunjae95 @MiranLeeeee @oranjik 
[TLVB-46](https://github.com/prgrms-web-devcourse/Team_Everevent_Kazedon_FE/pull/29)에서 선재님의 의견에 따라 폰트를 적용하던 중, 폰트 적용이 제대로 안 되던 현상을 해결 완료했습니다!
일단 이런 식으로 기술 부채라던지, 아직 해결되지 않은 문제들을 팀끼리 공유했으면 좋겠어요 :)
앞으로도 이런 양식으로 이슈를 올리고 스스로 해결 과정을 전개하면서, 팀끼리 리뷰하며 해결해 보아요~

**Comment by Sunjae95** [comment]
고생하셨습니다! 저도 찾고있어쓴데 확실하지 않아서 공유를 못하고 있었네요! 고생하셨습니다!
